// Export pages
export '/ui/authentication/sign_in/sign_in_page.dart' show SignInPage;
export '/ui/authentication/sign_up/sign_up_page.dart' show SignUpPage;
export '/ui/config/edit_profile_page/edit_profile_page.dart' show EditProfilePage;
export '/ui/authentication/forgot_password/forgot_password_page.dart' show ForgotPasswordPage;
export '/ui/home/home_page/home_page.dart' show HomePage;
export 'ui/config/profile_page/profile_page.dart' show ProfilePage;
export '/ui/meditation/meditation_home_page/meditation_home_page.dart' show MeditationHomePage;
export '/ui/notification/notification_list_page/notification_list_page.dart' show NotificationListPage;
export '/ui/notification/notification_view_page/notification_view_page.dart' show NotificationViewPage;
export '/ui/authentication/social_login/social_login_page.dart' show SocialLoginPage;
export '/ui/config/config_page/config_page.dart' show ConfigPage;
export '/ui/config/about_page/about_page.dart' show AboutPage;
export '/ui/authentication/change_email_page/change_email_page.dart' show ChangeEmailPage;
export '/ui/config/app_review_page/app_review_page.dart' show AppReviewPage;
export '/ui/config/settings_page/settings_page.dart' show SettingsPage;
export '/ui/config/invite_page/invite_page.dart' show InvitePage;
export '/ui/config/delete_account_page/delete_account_page.dart' show DeleteAccountPage;
export '/ui/config/about_authors_page/about_authors_page.dart' show AboutAuthorsPage;
export '/ui/config/alarm_page/alarm_page.dart' show AlarmPage;
export '/ui/meditation/meditation_details_page/meditation_details_page.dart' show MeditationDetailsPage;
export '/ui/meditation/meditation_play_page/meditation_play_page.dart' show MeditationPlayPage;
export '/ui/meditation/meditation_list_page/meditation_list_page.dart' show MeditationListPage;
export '/ui/video/video_home_page/video_home_page.dart' show VideoHomePage;
export '/ui/video/youtube_player_page/youtube_player_page.dart' show YoutubePlayerPage;
export '/ui/video/congresso_list_page/congresso_list_page.dart' show CongressoListPage;
export '/ui/video/entrevistas_list_page/entrevistas_list_page.dart' show EntrevistasListPage;
export '/ui/agenda/agenda_home_page/agenda_home_page.dart' show AgendaHomePage;
export '/ui/mensagens/mensagens_home_page/mensagens_home_page.dart' show MensagensHomePage;
export '/ui/agenda/agenda_list_page/agenda_list_page.dart' show AgendaListPage;
export '/ui/agenda/event_details_page/event_details_page.dart' show EventDetailsPage;
export '/ui/agenda/event_list_page/event_list_page.dart' show EventListPage;
export '/ui/mensagens/mensagem_details_page/mensagem_details_page.dart' show MensagemDetailsPage;
export '/ui/mensagens/mensagem_show_page/mensagem_show_page.dart' show MensagemShowPage;
export '/ui/meditation/meditation_video_list_page/meditation_video_list_page.dart' show MeditationVideoListPage;
export '/ui/meditation/meditation_statistics_page/meditation_statistics_page.dart' show MeditationStatisticsPage;
export '/ui/playlist/playlist_list_page/playlist_list_page.dart' show PlaylistListPage;
export '/ui/playlist/playlist_details_page/playlist_details_page.dart' show PlaylistDetailsPage;
export '/ui/playlist/playlist_add_audios_page/playlist_add_audios_page.dart' show PlaylistAddAudiosPage;
export '/ui/playlist/selectinstrument_page/selectinstrument_page.dart' show SelectinstrumentPage;
export '/ui/playlist/select_music_page/select_music_page.dart' show SelectMusicPage;
export '/ui/playlist/select_meditations_page/select_meditations_page.dart' show SelectMeditationsPage;
export '/ui/playlist/select_device_music_page/select_device_music_page.dart' show SelectDeviceMusicPage;
export '/ui/playlist/playlist_save_page/playlist_save_page.dart' show PlaylistSavePage;
export '/ui/playlist/playlist_edit_page/playlist_edit_page.dart' show PlaylistEditPage;
export '/ui/playlist/playlist_edit_audios_page/playlist_edit_audios_page.dart' show PlaylistEditAudiosPage;
export '/ui/playlist/playlist_play_page_old/playlist_play_page_old.dart' show PlaylistPlayPageOldWidget;
export '/ui/mensagens/mensagens_semantic_search_page/mensagens_semantic_search_page.dart'
    show MensagensSemanticSearchPage;
export '/ui/video/canal_viver_list_page/canal_viver_list_page.dart' show CanalViverListPage;
export '/ui/video/palestras_list_page/palestras_list_page.dart' show PalestrasListPage;
export '/ui/config/support_page/support_page.dart' show SupportPage;
export '/ui/config/feedback_page/feedback_page.dart' show FeedbackPage;
export '/ui/config/feature_page/feature_page.dart' show FeaturePage;
export '/ui/config/donation_page/donation_page.dart' show DonationPage;
export '/ui/playlist/playlist_play_page/playlist_play_page.dart' show PlaylistPlayPage;

export '/ui/playlist/playlist_audio_play_page/playlist_audio_play_page.dart'
    show PlaylistAudioPlayPage;
export '/ui/desafio/home_desafio_page/home_desafio_page.dart' show HomeDesafioPage;
export '/ui/desafio/lista_etapas_page/lista_etapas_page.dart' show ListaEtapasPage;
export '/ui/desafio/desafio_play_page/desafio_play_page.dart' show DesafioPlayPage;
export '/ui/desafio/completou_meditacao_page/completou_meditacao_page.dart' show CompletouMeditacaoPage;
export '/ui/desafio/completou_mandala_page/completou_mandala_page.dart' show CompletouMandalaPage;
export '/ui/desafio/completou_brasao_page/completou_brasao_page.dart' show CompletouBrasaoPage;
export '/ui/desafio/visualizar_premio_page/visualizar_premio_page.dart' show VisualizarPremioPage;
export '/ui/desafio/desafio_onboarding_page/desafio_onboarding_page.dart' show DesafioOnboardingPage;
export '/ui/desafio/diario_meditacao_page/diario_meditacao_page.dart' show DiarioMeditacaoPage;
export '/ui/desafio/diario_detalhes_page/diario_detalhes_page.dart' show DiarioDetalhesPage;
export '/ui/desafio/conquistas_page/conquistas_page.dart' show ConquistasPage;

// EAD Module
export '/ui/ead/ead_home_page/ead_home_page.dart' show EadHomePage;
export '/ui/ead/catalogo_cursos_page/catalogo_cursos_page.dart' show CatalogoCursosPage;
export '/ui/ead/curso_detalhes_page/curso_detalhes_page.dart' show CursoDetalhesPage;
export '/ui/ead/meus_cursos_page/meus_cursos_page.dart' show MeusCursosPage;
export '/ui/ead/player_topico_page/player_topico_page.dart' show PlayerTopicoPage;
export '/ui/ead/quiz_page/quiz_page.dart' show QuizPage;
export '/ui/ead/certificado_page/certificado_page.dart' show CertificadoPage;
